// src/ui/components/App.tsx
import { useStore } from '@nanostores/react';
import { MessageTypes } from '~types/messages.ts';
import { AppContent } from '~ui/components/AppContent.tsx';
import { HelpLink } from '~ui/components/HelpLink.tsx';
import { LurkersLink } from '~ui/components/LurkersLink.tsx';
import { SettingsButton } from '~ui/components/SettingsButton.tsx';
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from '~ui/components/Tooltip.tsx';
import React, { useEffect } from 'react';

import { $isP3 } from '../stores/selected-nodes';

export const App: React.FC = () => {
  const isP3 = useStore($isP3);

  useEffect(() => {
    parent.postMessage(
      {
        pluginMessage: {
          type: MessageTypes.UiReady,
        },
      },
      '*'
    );
  }, []);

  return (
    <div className="flex h-full w-full select-none flex-col items-center p-1 pb-0 font-martianMono">
      <AppContent />

      <div className="mb-2 mt-auto flex w-full items-end px-1">
        <HelpLink />

        <div className="ml-auto flex items-center">
          {isP3 && (
            <Tooltip>
              <TooltipTrigger>
                <div className="flex items-center">
                  <p className="mr-3 rounded border-0.5 border-secondary-75 p-1 text-xxxs font-medium leading-[8px] text-secondary-75">
                    P3
                  </p>
                </div>
              </TooltipTrigger>
              <TooltipContent>File color profile</TooltipContent>
            </Tooltip>
          )}

          <SettingsButton />
        </div>
      </div>

      <div className="absolute bottom-0 left-1/2 -translate-x-1/2">
        <LurkersLink />
      </div>
    </div>
  );
};

// src/ui/components/App.svelte
<script lang="ts">
	import { MessageTypes } from '~types/messages';
	import { onMount } from 'svelte';

	import { isP3 } from '../stores/selected-nodes';
	import AppContent from './AppContent.svelte';
	import HelpLink from './HelpLink.svelte';
	import LurkersLink from './LurkersLink.svelte';
	import SettingsButton from './SettingsButton.svelte';
	import Tooltip from './Tooltip.svelte';

	onMount(() => {
		parent.postMessage(
			{
				pluginMessage: {
					type: MessageTypes.UiReady
				}
			},
			'*'
		);
	});
</script>

<div
	class="relative flex min-h-full w-full select-none flex-col items-center p-1 pb-0 font-martianMono"
>
	<AppContent />

	<div class="mb-2 mt-auto flex w-full items-end px-1">
		<HelpLink />

		<div class="ml-auto flex items-center">
			{#if $isP3}
				<Tooltip>
					{#snippet trigger()}
						<div style="mix-blend-mode: difference;" class="flex items-center">
							<p
								class="mr-3 rounded border-0.5 border-secondary-75 p-1 text-xxxs font-medium leading-[8px] text-secondary-75"
							>
								P3
							</p>
						</div>
					{/snippet}
					File color profile
				</Tooltip>
			{/if}

			<SettingsButton />
		</div>
	</div>

	<div class="absolute bottom-0 left-1/2 -translate-x-1/2">
		<LurkersLink />
	</div>
</div>
