// src/ui/components/AppContent.svelte
<script lang="ts">
  import EmptySelectionMessage from '~ui/components/EmptySelectionMessage.svelte';
  import InvalidBackgroundSelectionMessage from '~ui/components/InvalidBackgroundSelectionMessage.svelte';
  import Selection from '~ui/components/Selection.svelte';
  import SelectionsList from '~ui/components/SelectionsList.svelte';
  import UnprocessedBlendModesSelectionMessage from '~ui/components/UnprocessedBlendModesSelectionMessage.svelte';
  import {
    contrastConclusion,
    isEmptySelection,
    isInvalidBackground,
    isMultiSelection,
    isSingleSelection,
    isUnprocessedBlendModes,
  } from '~ui/stores/selected-nodes.ts';
  import { isEmpty } from '~utils/not-empty.ts';
</script>

{#if $isInvalidBackground}
  <InvalidBackgroundSelectionMessage />
{:else if $isUnprocessedBlendModes}
  <UnprocessedBlendModesSelectionMessage />
{:else if $isEmptySelection || isEmpty($contrastConclusion)}
  <EmptySelectionMessage />
{:else if $isMultiSelection}
  <SelectionsList contrastConclusion={$contrastConclusion} />
{:else if $isSingleSelection}
  {#if isEmpty($contrastConclusion[0])}
    <EmptySelectionMessage />
  {:else}
    <Selection
      id={$contrastConclusion[0].id}
      isLast={true}
      size="large"
      userSelection={$contrastConclusion[0]}
    />
  {/if}
{/if}

// src/ui/components/AppContent.tsx
import { useStore } from '@nanostores/react';
import { EmptySelectionMessage } from '~ui/components/EmptySelectionMessage.tsx';
import { InvalidBackgroundSelectionMessage } from '~ui/components/InvalidBackgroundSelectionMessage.tsx';
import { Selection } from '~ui/components/Selection.tsx';
import { SelectionsList } from '~ui/components/SelectionsList.tsx';
import { UnprocessedBlendModesSelectionMessage } from '~ui/components/UnprocessedBlendModesSelectionMessage.tsx';
import {
  $contrastConclusion,
  $isEmptySelection,
  $isInvalidBackground,
  $isMultiSelection,
  $isUnprocessedBlendModes,
} from '~ui/stores/selected-nodes.ts';
import { isEmpty } from '~utils/not-empty.ts';
import { type ReactElement } from 'react';

export const AppContent = (): ReactElement => {
  const isInvalidBackground = useStore($isInvalidBackground);
  const isEmptySelection = useStore($isEmptySelection);
  const isMultiSelection = useStore($isMultiSelection);
  const isUnprocessedBlendModes = useStore($isUnprocessedBlendModes);
  const contrastConclusion = useStore($contrastConclusion);

  if (isInvalidBackground) {
    return <InvalidBackgroundSelectionMessage />;
  }

  if (isUnprocessedBlendModes) {
    return <UnprocessedBlendModesSelectionMessage />;
  }

  if (isEmptySelection) {
    return <EmptySelectionMessage />;
  }

  if (isEmpty(contrastConclusion)) {
    return <EmptySelectionMessage />;
  }

  if (isMultiSelection) {
    return <SelectionsList contrastConclusion={contrastConclusion} />;
  } else {
    const pair = contrastConclusion[0];

    if (isEmpty(pair)) {
      return <EmptySelectionMessage />;
    }

    return <Selection id={pair.id} isLast size="large" userSelection={pair} />;
  }
};
