// src/ui/components/ColorIndicator.svelte
<script lang="ts">
  import ColorPreview from '~ui/components/ColorPreview.svelte';
  import { copy } from '~ui/services/use-copy-to-clipboard/useCopyToClipboard.ts';
  import { ThemeVariablesKeys } from '~ui/types';
  import {
    getFormatterForCSS,
    getFormatterForDisplaying,
  } from '~utils/colors/formatters.ts';
  import { type Oklch } from 'culori/fn';

  import { colorSpaceDisplayMode } from '../stores/color-space-display-mode.ts';
  import Tooltip from './Tooltip.svelte';

  interface ColorIndicatorProps {
    borderColor: string;
    fill: { hex: string; oklch: Oklch };
    indicatorColor: string;
    isBlended: boolean;
    textColor: string;
  }

  const {
    borderColor,
    fill,
    indicatorColor,
    isBlended,
    textColor,
  }: ColorIndicatorProps = $props();

  const formatColorForDisplay = $derived(
    getFormatterForDisplaying($colorSpaceDisplayMode)
  );
  const displayValue = $derived(formatColorForDisplay(fill.oklch));

  const formatColorForCSS = getFormatterForCSS($colorSpaceDisplayMode);
  const cssValue = formatColorForCSS(fill.oklch);
  let copied = $state('');
  const onCopy = (): void => {
    copied = cssValue;
    setTimeout(() => {
      copied = '';
    }, 2000);
  }
</script>

<Tooltip>
  {#snippet trigger()}
      <button
        style="--indicators-active: var({ThemeVariablesKeys.secondary24});
            --indicators-hover: var({ThemeVariablesKeys.secondary16});
            color: {indicatorColor};"
        class="interactive"
        type="button"
        use:copy
        oncopied={onCopy}
      >
        <div
          class="flex items-center rounded-[7px] p-1 hover:bg-indicatorsHover active:bg-indicatorsActive"
        >
          <div class="mr-2">
            <ColorPreview {borderColor} {indicatorColor} {isBlended} />
          </div>
          <span style:color="var({textColor})">{displayValue}</span>
        </div>
      </button>
  {/snippet}

  {#if copied}
    Copied!
  {:else}
    <span class="whitespace-nowrap">Copy as CSS</span>
  {/if}
</Tooltip>

// src/ui/components/ColorIndicator.tsx
import { useStore } from '@nanostores/preact';
import { ColorPreview } from '~ui/components/ColorPreview.tsx';
import { ThemeVariablesKeys } from '~ui/components/ThemeVariablesProvider.tsx';
import {
  getFormatterForCSS,
  getFormatterForDisplaying,
} from '~utils/colors/formatters.ts';
import { type Oklch } from 'culori/fn';
import { type ReactElement } from 'preact/compat';
import useClipboard from 'react-use-clipboard';

import { $colorSpaceDisplayMode } from '../stores/color-space-display-mode.ts';
import { Tooltip } from '~ui/components/Tooltip.tsx';

interface ColorIndicatorProps {
  borderColor: string;
  fill: { hex: string; oklch: Oklch };
  indicatorColor: string;
  isBlended: boolean;
  textColor: string;
}

export const ColorIndicator = ({
  borderColor,
  fill,
  indicatorColor,
  isBlended,
  textColor,
}: ColorIndicatorProps): ReactElement => {
  const colorSpaceDisplayMode = useStore($colorSpaceDisplayMode);

  const formatColorForDisplay = getFormatterForDisplaying(
    colorSpaceDisplayMode
  );
  const displayValue = formatColorForDisplay(fill.oklch);

  const formatColorForCSS = getFormatterForCSS(colorSpaceDisplayMode);
  const cssValue = formatColorForCSS(fill.oklch);

  const [isCopied, setCopied] = useClipboard(cssValue, {
    successDuration: 2000,
  });

  return (
    <Tooltip content={isCopied ? 'Copied!' : 'Copy as CSS'}>
      <button
        style={{
          // eslint-disable-next-line @typescript-eslint/ban-ts-comment
          '--indicators-active': `var(${ThemeVariablesKeys.secondary24})`,
          '--indicators-hover': `var(${ThemeVariablesKeys.secondary16})`,
          color: indicatorColor,
        }}
        className="interactive"
        onClick={setCopied}
        type="button"
      >
        <div className="flex items-center rounded-[7px] p-1 hover:bg-indicatorsHover active:bg-indicatorsActive">
          <div className="mr-2">
            <ColorPreview
              borderColor={borderColor}
              indicatorColor={indicatorColor}
              isBlended={isBlended}
            />
          </div>
          <span style={{ color: `var(${textColor})` }}>{displayValue}</span>
        </div>
      </button>
    </Tooltip>
  );
};
