// src/ui/components/ColorPreview.tsx
import { BasicColorPreviewIcon } from '~ui/components/BasicColorPreviewIcon.tsx';
import { LayeredColorPreviewIcon } from '~ui/components/LayeredColorPreviewIcon.tsx';
import { type ReactElement } from 'react';

interface Props {
  borderColor?: string;
  indicatorColor: string;
  isBlended?: boolean;
}

export const ColorPreview = ({
  borderColor,
  indicatorColor,
  isBlended,
}: Props): ReactElement => {
  if (isBlended === true) {
    return (
      <div className="flex">
        <LayeredColorPreviewIcon
          borderColor={borderColor}
          indicatorColor={indicatorColor}
        />
      </div>
    );
  }

  return (
    <BasicColorPreviewIcon
      borderColor={borderColor}
      indicatorColor={indicatorColor}
    />
  );
};

// src/ui/components/ColorPreview.svelte
<script lang="ts">
  import BasicColorPreviewIcon from '~ui/components/BasicColorPreviewIcon.svelte';
  import LayeredColorPreviewIcon from '~ui/components/LayeredColorPreviewIcon.svelte';

  interface Props {
    borderColor: string;
    indicatorColor: string;
    isBlended: boolean;
  }

  const { borderColor, indicatorColor, isBlended }: Props = $props();
</script>

{#if isBlended}
  <div class="flex">
    <LayeredColorPreviewIcon {borderColor} {indicatorColor} />
  </div>
{:else}
  <BasicColorPreviewIcon {borderColor} {indicatorColor} />
{/if}
