// src/ui/components/LurkersLink.tsx
import { LurkersIcon } from '~ui/components/LurkersIcon.tsx';
import { Tooltip } from '~ui/components/Tooltip.tsx';
import { type ReactElement } from 'preact/compat';

import { evilMartiansSiteURL } from '../../constants.ts';

export const LurkersLink = (): ReactElement => {
  return (
    <Tooltip content="Evil Martians">
      <a
        className="interactive"
        href={evilMartiansSiteURL}
        rel="noreferrer"
        target="_blank"
      >
        <LurkersIcon />
      </a>
    </Tooltip>
  );
};

// src/ui/components/LurkersLink.svelte
<script lang="ts">
	import LurkersIcon from '~ui/components/LurkersIcon.svelte';
	import Tooltip from '~ui/components/Tooltip.svelte';

	import { evilMartiansSiteURL } from '../../constants.ts';
</script>

<Tooltip>
	{#snippet trigger()}
		<a class="interactive" href={evilMartiansSiteURL} rel="noreferrer" target="_blank">
			<LurkersIcon />
		</a>
	{/snippet}
	<span class="whitespace-nowrap">Evil Martians</span>
</Tooltip>
