// src/ui/components/TextMetrics.tsx
import { ThemeVariablesKeys } from '~ui/components/ThemeVariablesProvider.tsx';
import { conclusions } from '~ui/services/apca/conclusion.ts';
import { fontLookupAPCA } from 'apca-w3';
import { type ReactElement } from 'react';

import { PictureIcon } from './PictureIcon.tsx';
import { StopIcon } from './StopIcon.tsx';
import { WarningIcon } from './WarningIcon.tsx';

interface Props {
  apca: number;
}

export const TextMetrics = ({ apca }: Props): ReactElement => {
  const [, , , , regular, , , bold] = fontLookupAPCA(apca);

  if (Math.abs(apca) < conclusions['Not Readable']) {
    return <StopIcon />;
  }

  if (Math.abs(apca) < conclusions['Non-Text']) {
    return <WarningIcon />;
  }

  if (Math.abs(apca) < conclusions['Large Text']) {
    return <PictureIcon />;
  }

  return (
    <div
      style={{
        color: `var(${ThemeVariablesKeys.fg})`,
      }}
      className="flex items-center"
    >
      <div className="mr-3 flex items-center">
        <p
          style={{
            borderColor: `var(${ThemeVariablesKeys.fg})`,
          }}
          className="mr-2 rounded border-0.5 p-1 text-xxxs font-medium leading-[8px]"
        >
          Rg
        </p>
        <p className="text-xxs leading-none">{regular}px</p>
      </div>
      <div className="flex items-center">
        <p
          style={{
            borderColor: `var(${ThemeVariablesKeys.fg})`,
          }}
          className="mr-2 rounded border-0.5 p-1 text-xxxs font-medium leading-[8px]"
        >
          Bd
        </p>
        <p className="text-xxs leading-none">{bold}px</p>
      </div>
    </div>
  );
};

// src/ui/components/TextMetrics.svelte
<script lang="ts">
	import PictureIcon from '~ui/components/PictureIcon.svelte';
	import StopIcon from '~ui/components/StopIcon.svelte';
	import WarningIcon from '~ui/components/WarningIcon.svelte';
	import { conclusions } from '~ui/services/apca/conclusion.ts';
	import { ThemeVariablesKeys } from '~ui/types';
	import { fontLookupAPCA } from 'apca-w3';

	interface Props {
		apca: number;
	}
	const { apca }: Props = $props();

	const [, , , , regular, , , bold] = fontLookupAPCA(apca);
</script>

{#if Math.abs(apca) < conclusions['Not Readable']}
	<StopIcon />
{:else if Math.abs(apca) < conclusions['Non-Text']}
	<WarningIcon />
{:else if Math.abs(apca) < conclusions['Large Text']}
	<PictureIcon />
{:else}
	<div style="color: var({ThemeVariablesKeys.fg})" class="flex items-center">
		<div class="mr-3 flex items-center">
			<p
				style="borderColor: var({ThemeVariablesKeys.fg})"
				class="mr-2 rounded border-0.5 p-1 text-xxxs font-medium leading-[8px]"
			>
				Rg
			</p>
			<p class="text-xxs leading-none">{regular}px</p>
		</div>
		<div class="flex items-center">
			<p
				style="borderColor: var({ThemeVariablesKeys.fg})"
				class="mr-2 rounded border-0.5 p-1 text-xxxs font-medium leading-[8px]"
			>
				Bd
			</p>
			<p class="text-xxs leading-none">{bold}px</p>
		</div>
	</div>
{/if}
