// src/ui/components/Tooltip.svelte
<script lang="ts">
  import type { Placement } from '@floating-ui/dom';
  import type { Snippet } from 'svelte';

  import { createFloatingActions } from 'svelte-floating-ui';
  import { flip, offset, shift } from 'svelte-floating-ui/dom';

  interface Props {
    children: Snippet;
    placement?: Placement;
    trigger: Snippet;
  }
  const { children, placement = 'top', trigger }: Props = $props();

  const [floatingRef, floatingContent] = createFloatingActions({
    autoUpdate: {
      ancestorResize: true,
      elementResize: true,
    },
    middleware: [
      offset(5),
      flip({
        fallbackAxisSideDirection: 'start',
        padding: 5,
      }),
      shift({ padding: 5 }),
    ],
    placement,
    strategy: 'absolute',
  });

  let showTooltip = $state(false);
</script>

<button
  onclick={() => (showTooltip = true)}
  onmouseenter={() => (showTooltip = true)}
  onmouseleave={() => (showTooltip = false)}
  use:floatingRef
>
  {@render trigger()}
</button>

{#if showTooltip}
  <div
    style="position:absolute"
    use:floatingContent
    class="rounded-full bg-black p-2 px-3 py-1.5 font-martianMono text-xxs font-medium text-white shadow-md dark:bg-white dark:text-black"
  >
    {@render children()}
  </div>
{/if}

// src/ui/components/Tooltip.tsx
import { useRef, useEffect, useState } from 'preact/compat';
import { useFloatingTooltip } from '~hooks/useFloatingTooltip.ts';
import { Placement } from '@floating-ui/dom';
import { ComponentChildren } from 'preact';

interface TooltipProps {
  children: ComponentChildren;
  content: ComponentChildren;
  placement?: Placement;
}

export const Tooltip = ({
  children,
  content,
  placement = 'top',
}: TooltipProps) => {
  const triggerRef = useRef<HTMLElement>(null);
  const tooltipRef = useRef<HTMLDivElement>(null);
  const openTimeout = useRef<number | null>(null);
  const closeTimeout = useRef<number | null>(null);

  const [visible, setVisible] = useState(false);

  useEffect(() => {
    if (visible && triggerRef.current && tooltipRef.current) {
      return useFloatingTooltip(
        triggerRef.current,
        tooltipRef.current,
        placement
      );
    }
  }, [visible]);

  const onMouseEnter = () => {
    if (closeTimeout.current) clearTimeout(closeTimeout.current);
    openTimeout.current = window.setTimeout(() => setVisible(true), 150);
  };

  const onMouseLeave = () => {
    if (openTimeout.current) clearTimeout(openTimeout.current);
    closeTimeout.current = window.setTimeout(() => setVisible(false), 0);
  };

  return (
    <div
      className={`relative`}
      onMouseEnter={onMouseEnter}
      onMouseLeave={onMouseLeave}
    >
      {children}
      {visible && (
        <div
          style={{
            top: 0,
            left: 0,
          }}
          ref={tooltipRef}
          className="absolute z-50 w-max rounded-full bg-black p-2 px-3 py-1.5 font-martianMono text-xxs font-medium text-white shadow-md transition-opacity dark:bg-white dark:text-black"
        >
          {content}
        </div>
      )}
    </div>
  );
};
